#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : httplib2
Version  : 0.19.0
Release  : 67
URL      : https://files.pythonhosted.org/packages/ed/ef/f0e05d5886a9c25dea4b18be06cd7bcaddbae0168cc576f3568f9bd6a35a/httplib2-0.19.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/ed/ef/f0e05d5886a9c25dea4b18be06cd7bcaddbae0168cc576f3568f9bd6a35a/httplib2-0.19.0.tar.gz
Summary  : A comprehensive HTTP client library.
Group    : Development/Tools
License  : MIT
Requires: httplib2-license = %{version}-%{release}
Requires: httplib2-python = %{version}-%{release}
Requires: httplib2-python3 = %{version}-%{release}
Requires: pyparsing
BuildRequires : buildreq-distutils3
BuildRequires : pyparsing

%description
A comprehensive HTTP client library, ``httplib2`` supports many features left out of other HTTP libraries.
        
        **HTTP and HTTPS**
          HTTPS support is only available if the socket module was compiled with SSL support.
        
        
        **Keep-Alive**
          Supports HTTP 1.1 Keep-Alive, keeping the socket open and performing multiple requests over the same connection if possible.
        
        
        **Authentication**
          The following three types of HTTP Authentication are supported. These can be used over both HTTP and HTTPS.
        
          * Digest
          * Basic
          * WSSE
        
        **Caching**

%package license
Summary: license components for the httplib2 package.
Group: Default

%description license
license components for the httplib2 package.


%package python
Summary: python components for the httplib2 package.
Group: Default
Requires: httplib2-python3 = %{version}-%{release}

%description python
python components for the httplib2 package.


%package python3
Summary: python3 components for the httplib2 package.
Group: Default
Requires: python3-core
Provides: pypi(httplib2)
Requires: pypi(pyparsing)

%description python3
python3 components for the httplib2 package.


%prep
%setup -q -n httplib2-0.19.0
cd %{_builddir}/httplib2-0.19.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1612799862
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python python2/httplib2test.py || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/httplib2
cp %{_builddir}/httplib2-0.19.0/LICENSE %{buildroot}/usr/share/package-licenses/httplib2/ad69fe8cc106ba1fc060d239d0483740bf66f1f9
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/httplib2/ad69fe8cc106ba1fc060d239d0483740bf66f1f9

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
